app = "hotel-voice-bot"
primary_region = "ord"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[machine]
  memory = 512
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  memory = 1024
  cpu_kind = "shared"
  cpus = 1
