app = "hotel-voice-bot-staging"
primary_region = "dfw"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["heroku/nodejs"]
  
[build.env]
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "development"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[deploy]
  release_command = "echo 'Deployment completed'"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
